### ISSUE TITLE
Make repo public todo list

### ISSUE THREAD

**Issue by michal-franc** [michal-franc/cir#1]
- [x] clean up readme
    - [x] example output - failed, successful
    - [x] installation
    - [x] explanation
    - [x] usage
    - [x] current limitations (only aws, only ec2 to ec2, only same vpc or vpc peering or tgw)
    - [ ] commands and their description (automated tool here?)
    - [x] IDEAS.md
    - [x] Cleanup TODODS
    - [x] remove sensitive data
    - [x] Contributing.md
- [x] support same vpc check
- [x] support tgw check
- [x] support vpc peering check
- [x] error handling
   - [x] missing aws creds
   - [x] validation of variables
